Registration
AliakseiPV/bookyto pull request #2
Opened 2023-05-22 15:37 UTC by AliakseiPV

2023-05-22 16:29 UTC, OUghTMS requested changes
🌷

2023-05-22 16:29 UTC, OUghTMS commented on client/src/components/pages/SignUp.jsx
> +                        onChangeHandler={(event) => emailValidation(event, setEmail, setEmailError)}
Try to avoid passing functions inside function arguments.

It is only acceptable when function is a component.
Like this line `onMouseEnter={() => setEmailFocus(true)}`

2023-05-22 16:29 UTC, OUghTMS commented on client/src/utils/validation.js
> +export const passwordValidation = (event, setPassword, setPasswordError) => {
This is not look like an util function. It has the context of the business logic of the application. In my mind utils looks like something dump. 
Example: 
```
isValueEmpty = (value) => Boolean
```
or
```
isValueEmail = (value) => Boolean
```
or
```
isValueWithSpecialCharacter = (value) => Boolean
```

2023-05-22 16:29 UTC, OUghTMS commented on client/src/utils/validation.js
> +export const emailValidation = (event, setEmail, setEmailError) => {
This is not look like an util function. It has the context of the business logic of the application. In my mind utils looks like something dump. 
Example: 
```
isValueEmpty = (value) => Boolean
```
or
```
isValueEmail = (value) => Boolean
```
or
```
isValueWithSpecialCharacter = (value) => Boolean
```

2023-05-22 16:29 UTC, OUghTMS commented on client/src/utils/validation.js
> +        }
```
        for (let element of emailErrors) {
            if (!element.filter.test(String(emailValue))) {
                setEmailError(errors => [...errors, element.error])
            }
        }
```
This is a code duplicating. Try to avoid.

2023-05-22 16:29 UTC, OUghTMS commented on client/src/utils/validation.js
> +        }
```
        for (let element of regexCheck) {
            if (!element.filter.test(String(passwordValue))) {
                setPasswordError(errors => [...errors, element.error])
            }
        }
```
This is a code duplicating. Try to avoid.

2023-05-22 16:29 UTC, OUghTMS commented on client/src/components/pages/SignUp.jsx
> +    const [repeatPasswordFocus, setRepeatPasswordFocus] = useState(false)
```
    const [firstName, setFirstName] = useState('')
    const [lastName, setLastName] = useState('')
    const [email, setEmail] = useState('')
    const [password, setPassword] = useState('')
    const [repeatPassword, setRepeatPassword] = useState('')
    const [emailError, setEmailError] = useState(['Email field is empty'])
    const [passwordError, setPasswordError] = useState(['Password is empty'])
    const [repeatPasswordError, setRepeatPasswordError] = useState(['Password is empty'])
    const [disableButton, setDisableButton] = useState(true)
    const [emailFocus, setEmailFocus] = useState(false)
    const [passwordFocus, setPasswordFocus] = useState(false)
    const [repeatPasswordFocus, setRepeatPasswordFocus] = useState(false)
```
I think that this isn't a last form in your application. And every time you create new form, you will duplicate a lot of states and the same functionality about focusing, errors and value storing. Try to think about such component like `<Form />` and/or `<FormItem />`.

Example:
```
<FormItem
    intialValue=""
    validate={(value) => 'Error value'}
    name="firstName"
/>
```

2023-05-23 11:20 UTC, AliakseiPV commented on client/src/components/pages/SignUp.jsx
> +            setDisableButton(true);
Done

2023-05-23 11:24 UTC, AliakseiPV commented on client/src/components/pages/SignUp.jsx
> +import FormInput from '../FormInput/FormInput';
Done

2023-05-23 11:33 UTC, AliakseiPV commented on client/src/utils/validation.js
> +export const passwordValidation = (event, setPassword, setPasswordError) => {
Done

2023-05-23 11:34 UTC, AliakseiPV commented on client/src/utils/validation.js
> +export const emailValidation = (event, setEmail, setEmailError) => {
Done

2023-05-23 11:40 UTC, AliakseiPV commented on client/src/utils/validation.js
> +        }
Done

2023-05-23 11:40 UTC, AliakseiPV commented on client/src/utils/validation.js
> +        }
Done

2023-05-24 10:23 UTC, AliakseiPV commented on client/src/components/pages/SignUp.jsx
> +                        onChangeHandler={(event) => emailValidation(event, setEmail, setEmailError)}
Done

2023-05-24 10:24 UTC, AliakseiPV commented on client/src/components/pages/SignUp.jsx
> +    const [repeatPasswordFocus, setRepeatPasswordFocus] = useState(false)
Done

2023-05-26 10:30 UTC, OUghTMS requested changes
💀

2023-05-26 10:30 UTC, OUghTMS commented on client/src/components/Form.jsx
> +            <Button
This is not a part of `Form` component

2023-05-26 10:30 UTC, OUghTMS commented on client/src/components/Form.jsx
> +    const [form, setForm] = useState(initialValues)
Why form is value??
or 
Why value is form??

2023-05-26 10:30 UTC, OUghTMS commented on client/src/components/Form.jsx
> +        if (name === 'repeatPassword') {
What is repeatPassword? Form shouldn't know about FormItem names

2023-05-26 10:30 UTC, OUghTMS commented on client/src/components/Form.jsx
> +    const [inputErrors, setInputErrors] = useState(new Map())
Why `new Map()` is better than common object?

2023-05-26 10:30 UTC, OUghTMS commented on client/src/components/Form.jsx
> +            </FormContext.Provider>
Let's
```
        
            <FormContext.Provider value={{
                form, handleChange, inputErrors
            }}>
<form onSubmit={onSubmit}>
                {children}
</form>
            </FormContext.Provider>
```

2023-05-26 10:30 UTC, OUghTMS commented on client/src/components/Form.jsx
> +                form, handleChange, inputErrors
rename 
form -> values
handleChange -> setValues
inputErrors -> errors

2023-05-26 19:32 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +                form, handleChange, inputErrors
Done

2023-05-26 19:32 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +        if (name === 'repeatPassword') {
Done

2023-05-26 19:32 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +    const [form, setForm] = useState(initialValues)
Done

2023-05-26 19:38 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +    const [form, setForm] = useState(initialValues)
Done

2023-05-27 09:42 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +            <Button
Done

2023-05-27 09:45 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +            </FormContext.Provider>
Done

2023-05-27 09:56 UTC, OUghTMS commented on client/src/components/Form.jsx
> +            </FormContext.Provider>
pizdaball

2023-05-27 10:08 UTC, OUghTMS requested changes

2023-05-27 10:08 UTC, OUghTMS commented on client/src/helpers/validation.js
> +export const signUpValidation = (errorChecks, inputName, currentInputValue, errors, setErrors, setButtonDisable, password, repeatPassword) => {
too many arguments. Looks like crap...

2023-05-27 10:08 UTC, OUghTMS commented on client/src/helpers/validation.js
> +export const signUpValidation = (errorChecks, inputName, currentInputValue, errors, setErrors, setButtonDisable, password, repeatPassword) => {
signUpValidation is a business name. Shouldn't be in a common (anonymous) utils.

2023-05-27 10:08 UTC, OUghTMS commented on client/src/components/Form.jsx
> +            <Button
pizdaball

2023-05-27 10:09 UTC, OUghTMS commented on client/src/components/Form.jsx
> +        if (name === 'repeatPassword') {
Pizdaball

2023-05-27 10:13 UTC, OUghTMS commented on client/src/components/Form.jsx
> +                form, handleChange, inputErrors
handleChange -> onChange ❌ wrong (This is not a listener (or event listener). This is a form util, witch give you ability to set value)
handleChange -> setValue ✔️ correct

2023-05-27 11:12 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +                form, handleChange, inputErrors
Done

2023-05-27 11:47 UTC, AliakseiPV commented on client/src/helpers/validation.js
> +export const signUpValidation = (errorChecks, inputName, currentInputValue, errors, setErrors, setButtonDisable, password, repeatPassword) => {
Done

2023-05-29 18:37 UTC, OUghTMS requested changes

2023-05-29 18:37 UTC, OUghTMS commented on client/src/components/Form/Form.jsx
> +            values, changeHandler, errors
handleChange -> onChange ❌ wrong (This is not a listener (or event listener). This is a form util, witch give you ability to set value)
handleChange -> setValues ✔️ correct

2023-05-29 18:37 UTC, OUghTMS commented on client/src/components/Form/Form.jsx
> +    const changeHandler = async (event) => {
const changeHandler = async (event) => {
to 
const setValuesHandler = (name, value) => {

2023-05-29 18:37 UTC, OUghTMS commented on client/src/components/Form/Form.jsx
> +    const changeHandler = async (event) => {
`name` and `value` arguments are more useable then `event`. Can you create `event` without < Input >?

2023-05-29 18:37 UTC, OUghTMS commented on client/src/components/Form/Form.scss
> +.Form_default {
This class isn't used in `Form` component

2023-05-29 18:37 UTC, OUghTMS commented on client/src/components/FormItem.jsx
> +import '../pages/Styles/SignUp.scss'
SignUp.scss in FormItem.jsx? wtf? how are they related?

2023-05-29 18:37 UTC, OUghTMS commented on client/src/helpers/validation.js
> +// const checkForErrors = (errorsMap) => {
remove comments

2023-05-29 18:37 UTC, OUghTMS commented on client/src/pages/SignUp.jsx
> +                    classNameInput={'Input'}
Use same code style with props everywhere
like this:
```
typeInput='firstName'
```
or this
```
classNameInput={'Input'}
```

2023-05-29 18:37 UTC, OUghTMS commented on client/src/ui-kit/Button/Button.scss
> +.Button {
This class isn't used in `Button` component

2023-05-29 18:37 UTC, OUghTMS commented on client/src/ui-kit/Input/Input.scss
> +.Input {
This class isn't used in `Input` component

2023-05-29 18:37 UTC, OUghTMS commented on client/src/ui-kit/Label/Label.scss
> +.Label {
This class isn't used in `Label` component

2023-05-31 17:16 UTC, OUghTMS requested changes

2023-05-31 17:16 UTC, OUghTMS commented on client/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500&display=swap" rel="stylesheet">
Add fonts using `npm`

2023-05-31 17:16 UTC, OUghTMS commented on client/src/components/Form/Form.jsx
> +            values, setValuesHandler, errors, setErrors, validationParams
`setValuesHandler` -> `setValues: setValuesHandler`  🏃

2023-05-31 17:16 UTC, OUghTMS commented on client/src/pages/SignUp.jsx
> +import '../pages/Styles/SignUp.scss'
Just create a folder SignUp for SignUp.scss and SignUp.jsx

2023-06-03 17:59 UTC, AliakseiPV commented on client/src/components/Form.jsx
> +    const [inputErrors, setInputErrors] = useState(new Map())
Done

2023-06-03 17:59 UTC, AliakseiPV commented on client/src/components/Form/Form.jsx
> +            values, changeHandler, errors
Done

2023-06-03 17:59 UTC, AliakseiPV commented on client/src/components/Form/Form.jsx
> +    const changeHandler = async (event) => {
Done

2023-06-03 18:02 UTC, AliakseiPV commented on client/src/components/Form/Form.scss
> +.Form_default {
Done

2023-06-03 18:02 UTC, AliakseiPV commented on client/src/components/FormItem.jsx
> +import '../pages/Styles/SignUp.scss'
Done

2023-06-03 18:02 UTC, AliakseiPV commented on client/src/helpers/validation.js
> +// const checkForErrors = (errorsMap) => {
Done

2023-06-03 18:04 UTC, AliakseiPV commented on client/src/pages/SignUp.jsx
> +                    classNameInput={'Input'}
Done

2023-06-03 18:04 UTC, AliakseiPV commented on client/src/ui-kit/Button/Button.scss
> +.Button {
Done

2023-06-03 18:04 UTC, AliakseiPV commented on client/src/ui-kit/Input/Input.scss
> +.Input {
Done

2023-06-03 18:04 UTC, AliakseiPV commented on client/src/ui-kit/Label/Label.scss
> +.Label {
Done

2023-06-03 18:05 UTC, AliakseiPV commented on client/src/pages/SignUp.jsx
> +import '../pages/Styles/SignUp.scss'
Done

2023-06-03 18:28 UTC, AliakseiPV commented on client/public/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@400;500&display=swap" rel="stylesheet">
Done

2023-06-03 18:31 UTC, AliakseiPV commented on client/src/components/Form/Form.jsx
> +            values, setValuesHandler, errors, setErrors, validationParams
Done

2023-06-04 10:07 UTC, OUghTMS requested changes

2023-06-04 10:07 UTC, OUghTMS commented on client/src/ui-kit/Label/Label.jsx
> +       <label htmlFor={htmlFor} className={`Label ${className}`}>
Please use `classnames` npm package. It helps to avoid strange className values like undefined or null

Like `className={classnames('Label', className)}`

2023-06-04 10:07 UTC, OUghTMS commented on client/src/routes.js
> +import SignUp from './pages/SignUp/SignUp'
import SignUp from './pages/SignUp

2023-06-04 11:04 UTC, AliakseiPV commented on client/src/components/FormItem/FormItem.jsx
> +                        <></>
Done

2023-06-04 11:04 UTC, AliakseiPV commented on client/src/components/FormItem/FormItem.scss
> +}
Done

2023-06-04 11:05 UTC, AliakseiPV commented on client/src/pages/SignUp/SignUp.scss
> +.SignUp__Link {
Done

2023-06-04 11:05 UTC, AliakseiPV commented on client/src/ui-kit/Label/Label.jsx
> +       <label htmlFor={htmlFor} className={`Label ${className}`}>
Done

2023-06-04 11:05 UTC, AliakseiPV commented on client/src/routes.js
> +import SignUp from './pages/SignUp/SignUp'
Done

2023-06-05 12:25 UTC, merged